config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root 'pins#index'

  get "about" => "pages#about"

  resources :charges

  resources :purchases, only: [:show]

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates :image, presence: true
  validates :description, presence: true
  before_save :price_adjustment_for_stripe

  def price_adjustment_for_stripe
    self.price = (self.price * 100).to_i
  end

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  after_create :email_purchaser

  def to_param
    uuid
  end

  private
  def email_purchaser
    PurchaseMailer.purchase_receipt(self).deliver
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins

  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/charges_controller.rb
class ChargesController < ActionController::Base

  def create
  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :card  => params[:stripeToken]
  )
  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => params[:price],
    :description => 'Kocher HandbagStore Stripe customer',
    :currency    => 'GBP'
  )
  purchase = Purchase.create(
    email: params[:stripeEmail],
    card: params[:stripeToken],
    amount: params[:price],
    description: charge.description,
    currency: charge.currency,
    customer_id: customer.id,
    product_id: params[:product_id],
    uuid: SecureRandom.uuid.gsub('-','')
  )

  redirect_to purchase

  rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to charges_path
  end

  # def price_in_cents(amt)
  #   amt = (amt * 100).to_i
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:index]

  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @pins = Pin.all.order("created_at DESC")
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render :new
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find_by(id: params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :for_sale, :price)
    end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def show
    @purchase = Purchase.find_by_uuid(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/charges/create.html.erb
Purchase successfull

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
<%= link_to "Kocher HandBag's", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to 'New Product', new_pin_path %></li>
            <li><%= link_to "About", about_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              <li><%= link_to "Account Settings", edit_user_registration_path %></li>
            <% else %>
              <li><%= link_to "Sign in", new_user_session_path %></li>
            <% end %>
        </ul>
  </div><!-- /.navbar-collapse -->
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kocher Handbags</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://checkout.stripe.com/checkout.js"></script>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
  <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
     <% end %>
  </div>
<%= yield %>

</body>
</html>

app/views/layouts/purchase_mailer.html.erb
<!DOCTYPE html>
<html>
  <body>
    <%= yield %>
    <p>Thanks for buying</p>
  </body>
</html>

app/views/pages/about.html.erb
About Us

app/views/pages/home.html.erb
<div class="jumbotron center">
     <h1>Welcome to PinStore!<</h1>
     <% if user_signed_in? %>
          # do something
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control" %>
    </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :for_sale %>
    <%= f.check_box :for_sale, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %> in £
    <%= f.text_field :price, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %> <!-- pins loop start-->
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %><br/>
        <strong><%= pin.user.name if pin.user %></strong>
        <% if pin.user == current_user %> <!-- check current user loop start-->
          <br/><%= link_to 'Edit', edit_pin_path(pin) %> |
          <%= link_to 'Delete', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %> <!-- check current user loop end-->

        <% if pin.for_sale? && user_signed_in? %> <!-- for sale check loop start -->
      |  <button id='<%= "btn-buy-" + pin.id.to_s %>' type='button' class="btn btn-success btn-sm">Buy</button>

            <%= form_tag charges_path, id:'chargeForm' do %> <!-- chargeForm start -->
              <%= hidden_field_tag 'stripeToken' %>
              <%= hidden_field_tag 'stripeEmail' %>
              <%= hidden_field_tag 'product_id', pin.id %>
              <%= hidden_field_tag 'price', pin.price.to_i %>
              <!-- <a href="#" id='btn-buy'><strong>Buy This!</strong></a> -->
                <script>
                var handler = StripeCheckout.configure({
                  key: '<%= Rails.configuration.stripe[:publishable_key] %>',
                  token: function(token, arg) {
                    document.getElementById("stripeToken").value= token.id;
                    document.getElementById("stripeEmail").value= token.email;
                    document.getElementById("chargeForm").submit();
                  }
                });
                document.getElementById('<%= "btn-buy-" + pin.id.to_s %>').addEventListener('click', function(e){
                  handler.open({
                    name: '<%= pin.description %>',
                    currency: 'GBP',
                    description: '<%= pin.description %>' ,
                    amount: '<%= pin.price.to_i %>',
                    product_id: '<%= pin.id %>'
                  });
                  e.preventDefault();
                })
                </script>
            <% end %>  <!-- chargeForm end -->
        <% end %>  <!-- for sale check loop start -->

      </div>
    </div>
  <% end %> <!-- pins loop end-->
</div>

app/views/pins/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
<h1>New Product</h1>

<div class="panel-body">
  <%= render 'form' %>
</div>
<%= link_to 'Back', pins_path %>
</div>
</div>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <p><%= @pin.description %></p>
        <p><strong><%= @pin.user.name if @pin.user %></strong></p>
        <% if @pin.for_sale? %>
        <strong>This Item is for sale.<strong/>
        <% end %>
        <% if @pin.user == current_user %>
         <%= link_to 'Edit', edit_pin_path(@pin) %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/purchases/show.html.erb
<div class="container">
  <p>Thank you for your purchase</p>
  <div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Email</th>
        <th>Description</th>
        <th>Currency</th>
        <th>Purchased at</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @purchase.email %></td>
        <td><%= @purchase.description %></td>
        <td><%= @purchase.currency.upcase %></td>
        <td><%= @purchase.created_at %></td>
      </tr>
    </tbody>
  </table>
  </div>

  <a href='#'>Back to Store</a> | <a href=#>View all my purchases</a>
</div>